config/routes.rb
Rails.application.routes.draw do
  scope RailsCom.default_routes_scope do
    concern :my_ship do
      resources :addresses do
          collection do
            get :list
            post :select
            post :fork
            post :wechat
            post :program
            post :order
            post :order_from
            post :order_new
            post :order_create
            post :from_new
            post :from_create
          end
          member do
            get :join
          end
        end
      resources :carts, only: [] do
        resources :addresses, controller: 'cart/addresses' do
          collection do
            post :select
            get :cart
            get :station
            post :order
            post :order_new
            post :order_create
            post :fork
            post :wechat
            post :program
          end
          member do
            get :plans
          end
        end
      end
    end

    namespace :ship, defaults: { business: 'ship' } do
      resources :areas, only: [:index] do
        collection do
          get :search
          get :list
        end
        member do
          match :follow, via: [:get, :post]
          post :child
          post :input
        end
      end
      resources :box_hosts, only: [:index, :show] do
        collection do
          get :overview
          get :rent
          get :invest
        end
        member do
          get :all
          get :rentable
          get :rented
        end
        resources :boxes, only: [:index]
        resources :box_proxy_buys
        resources :box_proxy_sells
      end
      resources :boxes, only: [] do
        collection do
          post :in_create
        end
        member do
          get :qrcode
          get 'in' => :in_edit
          post 'in' => :in_update
        end
      end
      resources :shipments, only: [] do
        member do
          get :qrcode
        end
      end
      resources :packages, only: [] do
        member do
          get :qrcode
        end
      end
      namespace :panel, defaults: { namespace: 'panel' } do
        root 'home#index'
        resources :areas
        resources :lines do
          resources :similars
          resources :line_stations do
            member do
              patch :reorder
            end
          end
        end
        resources :stations
        resources :box_specifications do
          resources :boxes do
            collection do
              post :batch
              match :batch_pdf, via: [:get, :post]
            end
            member do
              get :pdf
            end
            resources :box_logs
            resources :rents do
              member do
                get :promote
                get :job
                put :compute
              end
            end
          end
          resources :box_hosts
        end
      end
      namespace :admin, defaults: { namespace: 'admin' } do
        resources :stations do
          member do
            get :lines
            get :shipments
          end
          collection do
            post :select
          end
        end
        resources :users, only: [:index]
        resources :addresses do
          collection do
            get :from
            get :packaged
            post :search
          end
        end
        resources :items, except: [:destroy] do
          collection do
            get 'address/:address_id' => :packable
            get 'packaged/:address_id' => :packaged
            get 'user/:user_id' => :user
          end
        end
        resources :packages do
          resources :packageds
          collection do
            get :address
          end
          member do
            get :pdf
            get :print_data
            get :shipment_items
          end
        end
        resources :cars
        resources :drivers
        resources :lines do
          resources :line_stations
          resources :shipments do
            member do
              get :stations
              get 'loaded/:from_station_id' => :loaded
              post 'loaded' => :loaded_create
              get 'unloaded/:station_id' => :unloaded
              post 'unloaded' => :unloaded_create
              get 'transfer/:station_id' => :transfer
              post :leave
              post :arrive
            end
            resources :shipment_items
            resources :shipment_logs
            resources :payment_orders do
              collection do
                get 'station/:station_id' => :station
              end
              member do
                get 'payment' => :payment_new
                post 'payment' => :payment_create
              end
            end
          end
        end
        resources :ways do
          resources :locations
        end
        resources :box_hosts do
          member do
            get :wallet
            patch 'wallet' => :update_wallet
          end
          resources :box_proxy_sells do
            resources :box_sells
          end
          resources :box_proxy_buys
          resources :box_holds
          resources :boxes do
            collection do
              post :batch
              match :batch_pdf, via: [:get, :post]
            end
            member do
              get :pdf
            end
            resources :box_logs
            resources :rents
          end
        end
        root 'home#index'
      end
      namespace :in, defaults: { namespace: 'in' } do
        resources :box_specifications, only: [:index, :show] do
          collection do
            get :buy
            get :rent
          end
        end
        resources :boxes do
          collection do
            get :invest
            get :rent
          end
          resources :box_logs
          resources :rents do
            member do
              get :promote
              get :job
              put :compute
              patch :finish
            end
          end
        end
        resources :orders do
          member do
            get :payment_types
            get 'payment_type' => :edit_payment_type
          end
          resources :items
        end
        resources :items
      end
      namespace :out, defaults: { namespace: 'out' } do
        resources :boxes do
          resources :rents
        end
      end
      namespace :our, defaults: { namespace: 'our' } do
        concerns :my_ship
        resources :orders do
          member do
            get :payment_types
            get 'payment_type' => :edit_payment_type
          end
          resources :items
        end
        resources :rents do
          member do
            get :promote
            get :job
            put :compute
          end
        end
        resources :boxes
      end
      namespace :dri, defaults: { namespace: 'dri' } do
        resources :favorites
      end
      namespace :me, defaults: { namespace: 'me' } do
        resources :packages do
          member do
            post :in
            post :out
            post :loaded
            post :unloaded
            post :package
            get :qrcode
          end
        end
        resources :boxes do
          member do
            post :in
            post :out
            get :qrcode
          end
          resources :rents do
            member do
              patch :finish
            end
          end
        end
        resources :cars do
          collection do
            post :package_in
            post :package_out
          end
          member do
            get :qrcode
          end
        end
        resources :shipments do
          member do
            post :loaded
            post :unloaded
            get :qrcode
          end
        end
      end
      namespace :agent, defaults: { namespace: 'agent' } do
        concerns :my_ship
      end
      namespace :my, defaults: { namespace: 'my' } do
        concerns :my_ship
        resource :driver
        resources :favorites
        resources :cars
        resources :ways do
          collection do
            get :requirement
            post :add
            post :select
          end
          resources :locations
        end
        resources :stations
        resources :box_holds do
          collection do
            get :sell
          end
          member do
            get :buy
          end
          resources :orders, only: [:create]
          resources :items, only: [:index, :show] do
            collection do
              get :rent
            end
          end
          resources :boxes
          resources :box_sells, only: [:index, :show, :create, :destroy]
        end
        resources :box_hosts, only: [] do
          resources :box_entrusts do
            collection do
              get :sell
            end
          end
        end
        resources :boxes, only: [] do
          collection do
            get :owned
            get :invest
          end
          member do
            get :qrcode
            get :owned_show
            post :start
          end
          resources :rents
        end
        resources :packages do
          member do
            get :qrcode
            put :wait
            post :receive
          end
        end
      end
    end
  end
  resolve 'Ship::BoxHost' do |box_host, options|
    [:ship, box_host, options]
  end
end

app/models/ship/model/shipment.rb
module Ship
  module Model::Shipment
    extend ActiveSupport::Concern

    included do
      attribute :type, :string
      attribute :expected_leave_at, :datetime
      attribute :expected_arrive_at, :datetime
      attribute :left_at, :datetime
      attribute :arrived_at, :datetime
      attribute :load_on, :date
      attribute :shipment_items_count, :integer, default: 0
      attribute :expected_minutes, :integer, comment: '预计路途分钟数'

      belongs_to :organ, class_name: 'Org::Organ', optional: true

      belongs_to :line
      belongs_to :car
      belongs_to :driver
      belongs_to :current_line_station, class_name: 'LineStation', optional: true
      belongs_to :shipping, polymorphic: true, optional: true

      has_many :line_stations, -> { order(position: :asc) }, primary_key: :line_id, foreign_key: :line_id
      has_many :shipment_items, dependent: :destroy_async
      has_many :shipment_logs, dependent: :destroy_async
      has_many :packages, through: :shipment_items
      has_many :loaded_shipment_items, -> { state_loaded }, class_name: 'ShipmentItem'
      has_many :loaded_packages, through: :loaded_shipment_items, source: :package
      has_many :unloaded_shipment_items, -> { state_unloaded }, class_name: 'ShipmentItem'
      has_many :unloaded_packages, through: :unloaded_shipment_items, source: :package
      has_many :boxes, through: :shipment_items
      has_many :payment_orders, through: :shipment_items

      enum :state, {
        preparing: 'preparing',
        prepared: 'prepared',
        left: 'left',
        arrived: 'arrived'
      }, prefix: true, default: 'preparing'

      before_create :init_current_station
      after_save_commit :sync_state_to_item, if: -> { saved_change_to_state? }
    end

    def init_current_station
      self.current_line_station ||= line.line_stations[0]
    end

    def change_state_to_left!
      self.current_line_station = current_line_station.next_item
      self.state = 'left'
      self.save
    end

    def change_state_to_arrived!
      self.state = 'arrived'
      self.save
    end

    def sync_state_to_item
      shipment_items.each do |shipment_item|
        shipment_item.state = 'unloaded'
        shipment_item.unloaded_at = Time.current
        shipment_item.save
      end
    end

    def enter_url
      Rails.application.routes.url_for(controller: 'ship/shipments', action: 'qrcode', id: self.id)
    end

    def qrcode_enter_url
      QrcodeHelper.data_url(enter_url)
    end

  end
end

app/models/ship/shipment.rb
module Ship
  class Shipment < ApplicationRecord
    include Model::Shipment
  end
end

app/controllers/ship/admin/shipments_controller.rb
module Ship
  class Admin::ShipmentsController < Admin::BaseController
    before_action :set_line
    before_action :set_cars, :set_lines, :set_drivers, only: [:new, :create, :edit, :update]
    before_action :set_shipment, only: [
      :show, :edit, :update, :destroy, :actions, :leave, :arrive,
      :stations, :unloaded, :unloaded_create, :transfer, :loaded, :loaded_create
    ]
    before_action :set_new_shipment, only: [:new, :create]
    before_action :set_station, only: [:unloaded, :transfer]
    before_action :set_from_line_station, only: [:loaded]
    before_action :set_shipment_log, only: [:leave, :arrive]

    def index
      q_params = {}

      @shipments = @line.shipments.includes(:car, :driver, current_line_station: :station).default_where(q_params).order(load_on: :desc).page(params[:page])
    end

    def new
      @shipment.load_on = Date.today
    end

    def leave
      @shipment_log.left_at = Time.current
      @shipment_log.save
    end

    def arrive
      @shipment_log.arrived_at = Time.current
      @shipment_log.save
    end

    def stations
      @line_stations = @shipment.line.line_stations.includes(:station)
    end

    def loaded
      q_params = {}
      q_params.merge! params.permit(:from_station_id, :station_id)

      @packages = Package.where(current_shipment_id: [@shipment.id, nil]).includes(:station, address: :area).default_where(q_params).order(id: :desc).page(params[:page])
    end

    def loaded_create
      packages = Package.find params[:ids].split(',')

      ss = packages.map do |package|
        si = @shipment.shipment_items.find_or_initialize_by(package_id: package.id)
        si.state = 'loaded'
        si.confirm_mode = 'batch'
        si.loaded_at ||= Time.current
        si
      end
      @shipment.class.transaction do
        ss.each(&:save)
      end
    end

    def unloaded
      q_params = {}
      q_params.merge! params.permit(:station_id)

      @packages = @shipment.packages.includes(:station, address: :area).default_where(q_params).order(id: :desc).page(params[:page])
    end

    def unloaded_create
      packages = Package.find params[:ids].split(',')

      ss = packages.map do |package|
        si = @shipment.shipment_items.find_or_initialize_by(package_id: package.id)
        si.state = 'unloaded'
        si.confirm_mode = 'batch'
        si.unloaded_at ||= Time.current
        si
      end
      @shipment.class.transaction do
        ss.each(&:save)
      end
    end

    def transfer
      q_params = {
      }

      @packages = @shipment.packages.where.not(station_id: @shipment.line.line_stations.pluck(:station_id)).default_where(q_params).page(params[:page])
    end

    private
    def set_cars
      @cars = Car.default_where(default_params)
    end

    def set_line
      @line = Line.find params[:line_id]
    end

    def set_lines
      @lines = Line.default_where(default_params)
    end

    def set_drivers
      @drivers = Driver.default_where(default_params)
    end

    def set_shipment
      @shipment = Shipment.find params[:id]
    end

    def set_new_shipment
      @shipment = @line.shipments.build(shipment_params)
    end

    def set_from_line_station
      @line_station = @shipment.line.line_stations.find_by station_id: params[:from_station_id]
    end

    def set_station
      @station = Station.find params[:station_id]
    end

    def set_shipment_log
      @shipment_log = @shipment.shipment_logs.find_or_initialize_by(station_id: params[:station_id])
    end

    def shipment_params
      p = params.fetch(:shipment, {}).permit(
        :driver_id,
        :car_id,
        :name,
        :load_on,
        :expected_leave_at,
        :left_at,
        :expected_arrive_at,
        :arrived_at
      )
      p.merge! default_form_params
    end

  end
end

app/controllers/ship/me/shipments_controller.rb
module Ship
  class Me::ShipmentsController < Me::BaseController
    before_action :set_shipment, only: [:qrcode, :loaded, :unloaded]
    before_action :set_box_from_scan, :set_package_from_scan, only: [:loaded, :unloaded]

    def index
      q_params = {}
      q_params.merge! params.permit(:address_id)

      @shipments = Shipment.includes(:shipmentds, :address).default_where(q_params).page(params[:page])
    end

    def loaded
      if @box
        @box.packages.state_box_in.each do |package|
          si = @shipment.shipment_items.find_or_initialize_by(box_id: @box.id, package_id: package.id)
          si.state = 'loaded'
          si.loaded_at = Time.current
        end
      elsif @package
        si = @shipment.shipment_items.find_or_initialize_by(package_id: @package.id)
        si.state = 'loaded'
        si.loaded_at = Time.current
      end

      @shipment.save
    end

    def unloaded
      if @box
        @shipment.shipment_items.state_loaded.where(box_id: @box.id).each do |si|
          si.state = 'unloaded'
          si.unloaded_at = Time.current
          si.save
        end
      elsif @package
        si = @shipment.shipment_items.find_or_initialize_by(package_id: @package.id)
        si.state = 'unloaded'
        si.status = 'never_loaded' if si.new_record?
        si.unloaded_at = Time.current
      end

      @shipment.save
    end

    def qrcode
    end

    private
    def set_shipment
      @shipment = Shipment.find(params[:id])
    end

    def set_package_from_scan
      p = params[:result].scan(RegexpUtil.more_between('packages/', '/qrcode'))
      if p.present?
        @package = Package.find p[0]
      end
    end

    def set_box_from_scan
      b = params[:result].scan(RegexpUtil.more_between('boxes/', '/qrcode'))
      if b.present?
        @box = Box.find b[0]
      end
    end

    def shipment_params
      params.fetch(:shipment, {}).permit(
        :state,
        :expected_on
      )
    end

  end
end

app/views/ship/admin/shipments/_transfer/_breadcrumb.html.erb
<div class="breadcrumb has-succeeds-separator">
  <ul>
    <li><%= link_to t('ship.admin.shipments.index.title'), { action: 'index' } %></li>
    <li><span class="px-3"><%= @shipment.line.name %></span></li>
    <li><%= link_to t('ship.admin.shipments.stations.title'), { action: 'stations' } %></li>
    <li><span class="px-3"><%= @station.name %></span></li>
    <li class="is-active"><%= t('.title') %></li>
  </ul>
</div>

app/views/ship/admin/shipments/_transfer/_filter_table.html+phone.erb
<table class="table as-search">
  <tr>
    <td>
      <% @shipment.line.line_stations.each do |line_station| %>
        <%= link_to line_station.station.name, filter_params(station_id: line_station.station_id, except: [:id]), class: active_helper(station_id: line_station.station_id, active: 'button is-info', item: 'button is-light') %>
        <i class="fa-solid fa-right-long text-grey px-1"></i>
      <% end %>
    </td>
  </tr>
</table>

app/views/ship/admin/shipments/_transfer/_index_item.html+phone.erb
<td>
  <p><%= model.address.content %></p>
</td>
<td>
  <span><%= model.state_i18n %></span>
  <%= link_to({ controller: 'admin/shipment_items', action: 'show', shipment_id: model.shipment_item.shipment_id, id: model.shipment_item.id }, data: { turbo_frame: 'modal' }) do %>
    <i class="fa-solid fa-location-arrow"></i>
  <% end if model.shipment_item %>
</td>
<td>
  <p><%= model.box&.code %></p>
  <p class="text-info-dark"><time data-controller="time"><%= model.boxed_in_at&.to_fs(:iso8601) %></time></p>
  <p class="text-warning-dark"><time data-controller="time"><%= model.boxed_out_at&.to_fs(:iso8601) %></time></p>
</td>
<td><time data-controller="time"><%= model.created_at.to_fs(:iso8601) %></time></td>

app/views/ship/admin/shipments/_transfer/_index_item_actions.html+phone.erb
<div class="media">
  <div class="media-content">
    <%= yield %>
  </div>
  <div class="weui-media-box__ft pr-2">
    <%= check_box_tag 'xx', model.id, @shipment.loaded_package_ids.include?(model.id), id: nil %>
  </div>
</div>

app/views/ship/admin/shipments/_transfer/_index_list.html+phone.erb
<div class="box is-padding-less">
  <div class="box-header">
    <div data-controller="check" data-check-name-value="xx" class="flex justify-content-right">
      <%= check_box_tag 'xxd', 'xx', false, id: nil, data: { action: 'check#toggleAll' } %>
      <%= form_with url: { action: 'loaded_create' }, method: :post, class: 'button_to ml-2' do |f| %>
        <%= f.hidden_field :ids, data: { check_target: 'ids' } %>
        <%= f.hidden_field :address_id, value: params[:address_id] %>
        <%= button_tag data: { action: 'check#doSubmit' }, aria: { label: t('.package') }, class: 'button is-small is-light' do %>
          <i class="fa-solid fa-person-dolly-empty text-danger"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="weui-panel__bd">
    <%= yield %>
  </div>
</div>

app/views/ship/admin/shipments/_transfer/_index_table.html+phone.erb
<div class="weui-panel">
  <div class="weui-panel__hd">
    <div data-controller="check" data-check-name-value="xx" class="is-flex is-justify-content-right">
      <%= check_box_tag 'xxd', 'xx', false, id: nil, data: { action: 'check#toggleAll' } %>
      <%= form_with url: { action: 'loaded_create' }, method: :post, class: 'button_to ml-2' do |f| %>
        <%= f.hidden_field :ids, data: { check_target: 'ids' } %>
        <%= f.hidden_field :address_id, value: params[:address_id] %>
        <%= button_tag data: { action: 'check#doSubmit' }, aria: { label: t('.package') }, class: 'button is-small is-light' do %>
          <i class="fa-solid fa-person-dolly-empty has-text-danger"></i>
        <% end %>
      <% end %>
    </div>
  </div>
  <div class="weui-panel__bd">
    <%= yield %>
  </div>
</div>

app/views/ship/admin/shipments/_transfer/_index_tbody.html+phone.erb
<td>
  <p><%= model.address.content %></p>
</td>
<td>
  <span><%= model.state_i18n %></span>
  <%= link_to({ controller: 'admin/shipment_items', action: 'show', shipment_id: model.shipment_item.shipment_id, id: model.shipment_item.id }, data: { turbo_frame: 'modal' }) do %>
    <i class="fa-solid fa-location-arrow"></i>
  <% end if model.shipment_item %>
</td>
<td>
  <p><%= model.box&.code %></p>
  <p class="has-text-info-dark"><time data-controller="time"><%= model.boxed_in_at&.to_fs(:iso8601) %></time></p>
  <p class="has-text-warning-dark"><time data-controller="time"><%= model.boxed_out_at&.to_fs(:iso8601) %></time></p>
</td>
<td><time data-controller="time"><%= model.created_at.to_fs(:iso8601) %></time></td>

app/views/ship/admin/shipments/_transfer/_index_tbody.html.erb
<td><%= check_box_tag 'xx', model.id, @shipment.loaded_package_ids.include?(model.id), id: nil %></td>
<td><%= model.station&.name %></td>
<td><%= model.address.content %></td>
<td>
  <span><%= model.state_i18n %></span>
  <%= link_to({ controller: 'admin/shipment_items', action: 'show', shipment_id: model.shipment_item.shipment_id, id: model.shipment_item.id }, data: { turbo_frame: 'modal' }) do %>
    <i class="fa-solid fa-location-arrow"></i>
  <% end if model.shipment_item %>
</td>
<td>
  <p><%= model.box&.code %></p>
  <p class="text-info-dark"><time data-controller="time"><%= model.boxed_in_at&.to_fs(:iso8601) %></time></p>
  <p class="text-warning-dark"><time data-controller="time"><%= model.boxed_out_at&.to_fs(:iso8601) %></time></p>
</td>
<td><time data-controller="time"><%= model.created_at.to_fs(:iso8601) %></time></td>

app/views/ship/admin/shipments/_transfer/_index_thead.html.erb
<th>
  <div data-controller="check" data-check-name-value="xx" class="flex align-items-center">
    <%= check_box_tag 'xxd', 'xx', false, id: nil, data: { action: 'check#toggleAll' } %>
    <%= form_with url: { action: 'loaded_create' }, method: :post, class: 'button_to ml-2' do |f| %>
      <%= f.hidden_field :ids, data: { check_target: 'ids' } %>
      <%= f.hidden_field :address_id, value: params[:address_id] %>
      <%= button_tag data: { action: 'check#doSubmit' }, aria: { label: t('.title') }, class: 'button is-small is-dark' do %>
        <i class="fa-solid fa-person-dolly-empty text-danger"></i>
      <% end %>
    <% end %>
  </div>
</th>
<th><%= Ship::Package.human_attribute_name(:station_id) %></th>
<th><%= Ship::Package.human_attribute_name(:address_id) %></th>
<th><%= Ship::Package.human_attribute_name(:state) %></th>
<th>
  <p><%= Ship::Package.human_attribute_name(:box_id) %></p>
  <p class="text-info-dark"><%= Ship::Package.human_attribute_name(:boxed_in_at) %></p>
  <p class="text-warning-dark"><%= Ship::Package.human_attribute_name(:boxed_out_at) %></p>
</th>
<th><%= Ship::Package.human_attribute_name(:created_at) %></th>

app/views/ship/admin/shipments/_transfer/_index_tr.html+phone.erb
<div class="weui-media-box weui-media-box_appmsg">
  <div class="weui-media-box__bd">
    <%= yield %>
  </div>
  <div class="weui-media-box__ft pr-2">
    <%= check_box_tag 'xx', model.id, @shipment.loaded_package_ids.include?(model.id), id: nil %>
  </div>
</div>

app/views/ship/admin/shipments/_transfer/_top_bar.html.erb
<div class="box as-bar">
  <%= link_to({ action: 'stations' }, class: 'px-4') do %>
    <i class="fa-solid fa-lg fa-fw-1 fa-angle-left"></i>
  <% end %>
  <div class="weui-title">
    <i class="fa-solid fa-person-dolly-empty text-danger"></i>
    <span class="pl-1"><%= t('.title') %></span>
  </div>
  <i class="px-5"></i>
</div>